# http://blogs.perl.org/users/alex_balhatchet/2013/04/travis-ci-perl.html
# http://perlmaven.com/skip-tests-if-prerequisite-not-installed 
language: perl
perl: [ "5.20" ]
pre_install:
    - sudo apt-get install libautodie-perl
install:
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla
    - cpanm --quiet --notest --skip-satisfied Pod::Coverage::TrustPod
    - cpanm --quiet --notest --skip-satisfied autodie
    - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
    - dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose
script:
    - dzil smoke --release --author
